### ISSUE TITLE
From zero where people will start. So we need to connect our repositories with these project.

### ISSUE THREAD

**Issue by hwpplayer1** [hwpplayers/tensorflow-hwpplayers-for-research#3]
Assembly, C and C++ comes at first.

**Comment by adhilcodes** [comment]
What is this issue I would  like to work on it

**Comment by hwpplayer1** [comment]
@adhilcodes I'm very happy that you replied our issue. Here our main goal is to provide a hackerspace and friendly development environment for beginners for everyone/public. 

So Here i started a discussion for technical questions.

I offer to start from basics like from the syntax of the language and to coding style and paradigms of this tensorflow project.

So first of all I need to listen your offer, maybe a question or exam for anyone.

Thanks Happy Hacking!
